server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/antte-shop
    username: root
    password: hclee
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
  devtools:
    livereload:
      enabled: true
decorator:
  datasource:
    p6spy:
      multiline: true
      log-file: logs/sql.log
      enable-logging: true
      logging: slf4j
      tracing.include-parameter-values: true
logging:
  file:
    path: logs